services:
  # Website Frontend
  app:
    image: pclub
    build:
      context: ./Programmingclub/
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=pclub
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - EXECUTOR_HOST=nginx
      - EXECUTOR_PORT=80
      - EXECUTOR_ROUTE=api/execute
    volumes:
      - .:/var/www/html
    entrypoint: ["sh", "-c", "php artisan migrate:fresh --seed && php artisan octane:start --host=0.0.0.0 --port=8000"]
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  # Database
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pclub
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  # Redis
  redis:
    image: redis:alpine
    networks:
      - app-network

  # Code Execution Backend
  executor:
    image: executor
    build:
      context: ./Orch/
    environment:
      - FLASK_ENV=production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/shm/:/dev/shm/
    networks:
      - app-network
    restart: always

  # Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - app-network
    depends_on:
      - app
      - executor

  # phpMyAdmin for Database Monitoring
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
